#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

# Requirement:

# Format: IP HTTP_CODE (check screenshot)

log_file="apache-access.log"

awk '{print $1, $9}' "$log_file"
